version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: pospassword
      POSTGRES_DB: posdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: golang:latest
    working_dir: /app
    volumes:
      - .:/app
    command: go run main.go
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
